Created Azure.Messaging.ServiceBus samples to be used by tutorials in DOCS
Azure/azure-service-bus pull request #394
Opened 2020-10-15 01:25 UTC by spelluru

## Description
Created Track 2 version of samples referred by these two tutorials in DOCS:

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-tutorial-topics-subscriptions-portal
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-to-event-grid-integration-example?tabs=v2

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] **I have read the [contribution guidelines](./CONTRIBUTING.md).**
- [X] Title of the pull request is clear and informative.
- [X] If applicable, the code is properly documented.
- [ X] The code builds without any errors.

2020-10-15 01:27 UTC, spelluru commented
@axisc

2020-10-15 06:09 UTC, SeanFeldman requested changes

2020-10-15 06:09 UTC, SeanFeldman commented on samples/DotNet/Azure.Messaging.ServiceBus/BasicSendReceiveTutorialwithFilters/BasicSendReceiveTutorialWithFilters/Extensions.cs
> +            return JsonConvert.DeserializeObject<T>(Encoding.UTF8.GetString(message.Body.ToBytes().ToArray()));
Any reason why [`System.Text.Json`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json) is not used?

2020-10-15 06:09 UTC, SeanFeldman commented on samples/DotNet/Azure.Messaging.ServiceBus/BasicSendReceiveTutorialwithFilters/BasicSendReceiveTutorialWithFilters/SendReceive.cs
> +                {
Is this scope needed? Could be done with `await using var client = new ServiceBusClient(...);`

2020-10-15 06:09 UTC, SeanFeldman commented on samples/DotNet/Azure.Messaging.ServiceBus/BasicSendReceiveTutorialwithFilters/BasicSendReceiveTutorialWithFilters/SendReceive.cs
> +            await using (ServiceBusClient client = new ServiceBusClient(ServiceBusConnectionString))
Same as above

2020-10-15 06:09 UTC, SeanFeldman commented on samples/DotNet/Azure.Messaging.ServiceBus/MessageSender/Program.cs
> +        const string ServiceBusConnectionString = "Endpoint=sb://spsbusegridtutns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=j1lrBlYD/6QXwC+OqYpByxoq6WZQ7Ig
Ooops

2020-10-15 06:09 UTC, SeanFeldman commented on samples/DotNet/Azure.Messaging.ServiceBus/MessageSender/Program.cs
> +                await using (ServiceBusClient client = new ServiceBusClient(ServiceBusConnectionString))
Same as above

2020-10-15 06:09 UTC, SeanFeldman commented on samples/DotNet/Azure.Messaging.ServiceBus/ServiceBusEventGridIntegrationV2/FunctionApp1/ReceiveMessagesOnEvent.cs
> +        const string ServiceBusConnectionString = "Endpoint=sb://spsbusegridtutns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=j1lrBlYD/6QXwC+OqYpByxoq6WZQ7Ig
Reset the key?

2020-10-15 13:32 UTC, spelluru commented
@SeanFeldman - Thanks for the feedback. Reset the key today :). I will fix other issues. I am trying to convert the Azure Function to v3.0 and use only Event Grid Trigger instead of HTTP trigger with the function. I will upload changes in a day or two.

2020-10-16 18:57 UTC, spelluru commented
@SeanFeldman - I have fixed the issues except the one about System.Text. I will look into it in another PR. Thanks.

2020-10-19 16:11 UTC, merged